[package]
name = "multicats"
version = "0.1.0"
edition = "2024"

[dependencies]
postcard = { version = "1.1.3", default-features = false }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.47.1", features = ["macros", "rt", "rt-multi-thread"] }
